name: Whiskers

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    uses: catppuccin/actions/.github/workflows/whiskers-check.yml@v1
    name: CI
    with:
      args: otty.tera
    secrets: inherit
